/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DepositRequestInput = IDL.Record({
  'userId' : IDL.Text,
  'utrNumber' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Text,
  'vipLevel' : IDL.Nat,
  'name' : IDL.Text,
  'mobile' : IDL.Text,
});
export const Game = IDL.Record({
  'betAmount' : IDL.Nat,
  'userId' : IDL.Text,
  'profitLoss' : IDL.Int,
  'timestamp' : Time,
  'gameName' : IDL.Text,
  'outcome' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DepositRequest = IDL.Record({
  'status' : IDL.Text,
  'userId' : IDL.Text,
  'timestamp' : Time,
  'utrNumber' : IDL.Text,
  'amount' : IDL.Nat,
});
export const User = IDL.Record({
  'referralCode' : IDL.Text,
  'balance' : IDL.Nat,
  'vipLevel' : IDL.Nat,
  'name' : IDL.Text,
  'referredBy' : IDL.Opt(IDL.Text),
  'mobile' : IDL.Text,
});
export const RegisterResult = IDL.Variant({
  'mobileAlreadyExists' : IDL.Null,
  'invalidMobileFormat' : IDL.Null,
  'internalError' : IDL.Null,
  'invalidReferralCode' : IDL.Null,
  'success' : User,
  'badRequest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveDeposit' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDepositRequest' : IDL.Func([DepositRequestInput], [IDL.Nat], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepositStatus' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getGameHistory' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getPaymentQR' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getPendingDeposits' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, DepositRequest))],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Text], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text], [User], []),
  'recordGameRound' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [RegisterResult],
      [],
    ),
  'resolveDepositRequest' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPaymentQR' : IDL.Func([ExternalBlob], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DepositRequestInput = IDL.Record({
    'userId' : IDL.Text,
    'utrNumber' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Text,
    'vipLevel' : IDL.Nat,
    'name' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const Game = IDL.Record({
    'betAmount' : IDL.Nat,
    'userId' : IDL.Text,
    'profitLoss' : IDL.Int,
    'timestamp' : Time,
    'gameName' : IDL.Text,
    'outcome' : IDL.Text,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DepositRequest = IDL.Record({
    'status' : IDL.Text,
    'userId' : IDL.Text,
    'timestamp' : Time,
    'utrNumber' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const User = IDL.Record({
    'referralCode' : IDL.Text,
    'balance' : IDL.Nat,
    'vipLevel' : IDL.Nat,
    'name' : IDL.Text,
    'referredBy' : IDL.Opt(IDL.Text),
    'mobile' : IDL.Text,
  });
  const RegisterResult = IDL.Variant({
    'mobileAlreadyExists' : IDL.Null,
    'invalidMobileFormat' : IDL.Null,
    'internalError' : IDL.Null,
    'invalidReferralCode' : IDL.Null,
    'success' : User,
    'badRequest' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveDeposit' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDepositRequest' : IDL.Func([DepositRequestInput], [IDL.Nat], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepositStatus' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getGameHistory' : IDL.Func([IDL.Text], [IDL.Vec(Game)], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getPaymentQR' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getPendingDeposits' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, DepositRequest))],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Text], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text], [User], []),
    'recordGameRound' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [RegisterResult],
        [],
      ),
    'resolveDepositRequest' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPaymentQR' : IDL.Func([ExternalBlob], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };