/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DepositRequest {
  'status' : string,
  'userId' : string,
  'timestamp' : Time,
  'utrNumber' : string,
  'amount' : bigint,
}
export interface DepositRequestInput {
  'userId' : string,
  'utrNumber' : string,
  'amount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Game {
  'betAmount' : bigint,
  'userId' : string,
  'profitLoss' : bigint,
  'timestamp' : Time,
  'gameName' : string,
  'outcome' : string,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type RegisterResult = { 'mobileAlreadyExists' : null } |
  { 'invalidMobileFormat' : null } |
  { 'internalError' : null } |
  { 'invalidReferralCode' : null } |
  { 'success' : User } |
  { 'badRequest' : null };
export type Time = bigint;
export interface User {
  'referralCode' : string,
  'balance' : bigint,
  'vipLevel' : bigint,
  'name' : string,
  'referredBy' : [] | [string],
  'mobile' : string,
}
export interface UserProfile {
  'referralCode' : string,
  'vipLevel' : bigint,
  'name' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveDeposit' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDepositRequest' : ActorMethod<[DepositRequestInput], bigint>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDepositStatus' : ActorMethod<[bigint], string>,
  'getGameHistory' : ActorMethod<[string], Array<Game>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getPaymentQR' : ActorMethod<[], [] | [ExternalBlob]>,
  'getPendingDeposits' : ActorMethod<[], Array<[bigint, DepositRequest]>>,
  'getUser' : ActorMethod<[string], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<[string], User>,
  'recordGameRound' : ActorMethod<[string, bigint, string, bigint], bigint>,
  'registerUser' : ActorMethod<[string, string, string], RegisterResult>,
  'resolveDepositRequest' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPaymentQR' : ActorMethod<[ExternalBlob], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];